version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  backend:
    build: ./node-backend
    ports:
      - "4000:4000"
    links:
      - mongo
  frontend:
    build: ./react-frontend
    ports:
      - "3000:3000"
    links:
      - backend